"""create table relationships

Revision ID: 381dace03da7
Revises: 
Create Date: 2023-11-18 15:31:45.448529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381dace03da7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('national_parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('national_park_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['national_park_id'], ['national_parks.id'], name=op.f('fk_trips_national_park_id_national_parks')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_trips_visitor_id_visitors')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('visitors')
    op.drop_table('national_parks')
    # ### end Alembic commands ###
